export type CraterPlaywrightApiOwner = "page" | "locator";

export type CraterPlaywrightApiStatus =
  | "supported"
  | "partial"
  | "crater-extension";

export type CraterPlaywrightApiEntry = {
  owner: CraterPlaywrightApiOwner;
  api: string;
  status: CraterPlaywrightApiStatus;
  notes: string;
};

export const CRATER_PLAYWRIGHT_API_SUPPORT = [
  {
    owner: "page",
    api: "connect",
    status: "supported",
    notes: "Connects to the Crater WebDriver BiDi endpoint and creates one tab context.",
  },
  {
    owner: "page",
    api: "close",
    status: "supported",
    notes: "Closes the current browsing context and WebSocket.",
  },
  {
    owner: "page",
    api: "url",
    status: "supported",
    notes: "Returns window.location.href from the current Crater runtime.",
  },
  {
    owner: "page",
    api: "title",
    status: "supported",
    notes: "Returns document.title.",
  },
  {
    owner: "page",
    api: "content",
    status: "supported",
    notes: "Returns document.documentElement.outerHTML.",
  },
  {
    owner: "page",
    api: "goto",
    status: "partial",
    notes: "Supports BiDi navigation, including data URLs. Browser-grade network loading is still limited.",
  },
  {
    owner: "page",
    api: "setContent",
    status: "supported",
    notes: "Loads HTML into Crater's DOM without executing embedded scripts.",
  },
  {
    owner: "page",
    api: "setContentWithScripts",
    status: "supported",
    notes: "Loads HTML and executes inline/classic/module scripts supported by Crater's runtime.",
  },
  {
    owner: "page",
    api: "setDefaultTimeout",
    status: "partial",
    notes: "Overrides timeout defaults for Crater polling-based wait helpers.",
  },
  {
    owner: "page",
    api: "loadPage",
    status: "partial",
    notes: "Fetches a URL through Crater runtime, parses HTML, and executes supported scripts; remote and module loading are still not browser-equivalent.",
  },
  {
    owner: "page",
    api: "addInitScript",
    status: "partial",
    notes: "Stores serializable init scripts and runs them before Crater executes page scripts.",
  },
  {
    owner: "page",
    api: "addScriptTag",
    status: "partial",
    notes: "Injects a script tag and executes content/url text in the Crater runtime.",
  },
  {
    owner: "page",
    api: "addStyleTag",
    status: "partial",
    notes: "Injects a style tag with content or fetched url text.",
  },
  {
    owner: "page",
    api: "evaluate",
    status: "supported",
    notes: "Runs script.evaluate and unwraps serialized values, with optional JSON-serializable arg support.",
  },
  {
    owner: "page",
    api: "$",
    status: "partial",
    notes: "Returns a Crater locator for the first matching element, not a Playwright ElementHandle.",
  },
  {
    owner: "page",
    api: "$$",
    status: "partial",
    notes: "Returns Crater locators for matching elements, not Playwright ElementHandles.",
  },
  {
    owner: "page",
    api: "$eval",
    status: "partial",
    notes: "Evaluates a serializable function against the first matching element.",
  },
  {
    owner: "page",
    api: "$$eval",
    status: "supported",
    notes: "Evaluates a function against querySelectorAll results.",
  },
  {
    owner: "page",
    api: "locator",
    status: "partial",
    notes: "Supports CSS plus text/role/placeholder/alt/title/testid/label selector shorthands.",
  },
  {
    owner: "page",
    api: "getByText",
    status: "partial",
    notes: "Text locator over Crater DOM direct text nodes with Playwright-style whitespace normalization.",
  },
  {
    owner: "page",
    api: "getByRole",
    status: "partial",
    notes: "Matches explicit roles, common native implicit roles, and basic accessible names; full ARIA role inference is not implemented.",
  },
  {
    owner: "page",
    api: "getByPlaceholder",
    status: "partial",
    notes: "Matches placeholder attributes.",
  },
  {
    owner: "page",
    api: "getByAltText",
    status: "partial",
    notes: "Matches alt attributes.",
  },
  {
    owner: "page",
    api: "getByTitle",
    status: "partial",
    notes: "Matches title attributes.",
  },
  {
    owner: "page",
    api: "getByTestId",
    status: "supported",
    notes: "Matches data-testid attributes.",
  },
  {
    owner: "page",
    api: "getByLabel",
    status: "partial",
    notes: "Matches simple label text and for/input relationships.",
  },
  {
    owner: "page",
    api: "click",
    status: "supported",
    notes: "Uses WebDriver BiDi input.performActions with a pointer source.",
  },
  {
    owner: "page",
    api: "fill",
    status: "supported",
    notes: "Sets value and dispatches input/change events.",
  },
  {
    owner: "page",
    api: "type",
    status: "supported",
    notes: "Focuses via click and sends keyDown/keyUp actions.",
  },
  {
    owner: "page",
    api: "press",
    status: "supported",
    notes: "Sends one keyDown/keyUp pair.",
  },
  {
    owner: "page",
    api: "hover",
    status: "supported",
    notes: "Uses pointerMove to the target element.",
  },
  {
    owner: "page",
    api: "drag",
    status: "supported",
    notes: "Uses pointer actions from source to target.",
  },
  {
    owner: "page",
    api: "check",
    status: "supported",
    notes: "Clicks an unchecked checkbox/radio-like element.",
  },
  {
    owner: "page",
    api: "uncheck",
    status: "supported",
    notes: "Clicks a checked checkbox-like element.",
  },
  {
    owner: "page",
    api: "select",
    status: "partial",
    notes: "Selects by option value using keyboard actions.",
  },
  {
    owner: "page",
    api: "selectOption",
    status: "partial",
    notes: "Playwright-style alias that selects a single option by value.",
  },
  {
    owner: "page",
    api: "textContent",
    status: "supported",
    notes: "Returns querySelector textContent.",
  },
  {
    owner: "page",
    api: "innerHTML",
    status: "supported",
    notes: "Returns querySelector innerHTML.",
  },
  {
    owner: "page",
    api: "inputValue",
    status: "supported",
    notes: "Returns querySelector value.",
  },
  {
    owner: "page",
    api: "isVisible",
    status: "partial",
    notes: "Checks hidden/display/visibility; full browser visibility semantics are not implemented.",
  },
  {
    owner: "page",
    api: "getAttribute",
    status: "supported",
    notes: "Returns querySelector getAttribute.",
  },
  {
    owner: "page",
    api: "count",
    status: "supported",
    notes: "Returns querySelectorAll length.",
  },
  {
    owner: "page",
    api: "waitForSelector",
    status: "supported",
    notes: "Polls querySelector until found.",
  },
  {
    owner: "page",
    api: "waitForText",
    status: "supported",
    notes: "Polls textContent until an exact string matches.",
  },
  {
    owner: "page",
    api: "waitForCondition",
    status: "supported",
    notes: "Polls a JavaScript expression until it returns truthy.",
  },
  {
    owner: "page",
    api: "route",
    status: "partial",
    notes: "Intercepts Crater runtime fetch() requests and supports fulfill/continue/abort decisions.",
  },
  {
    owner: "page",
    api: "unroute",
    status: "partial",
    notes: "Removes Crater runtime fetch() route handlers by matcher identity or clears all handlers.",
  },
  {
    owner: "page",
    api: "waitForFunction",
    status: "partial",
    notes: "Polls a serializable expression/function until it returns a truthy serialized value.",
  },
  {
    owner: "page",
    api: "waitForRequest",
    status: "partial",
    notes: "Waits for Crater runtime fetch() requests observed by the adapter network hook.",
  },
  {
    owner: "page",
    api: "waitForResponse",
    status: "partial",
    notes: "Waits for Crater runtime fetch() responses observed by the adapter network hook.",
  },
  {
    owner: "page",
    api: "waitForURL",
    status: "partial",
    notes: "Polls current URL against string, RegExp, or URL predicate matchers.",
  },
  {
    owner: "page",
    api: "waitForLoadState",
    status: "partial",
    notes: "load/domcontentloaded are immediate after Crater load; networkidle uses Crater runtime helpers.",
  },
  {
    owner: "page",
    api: "waitForNetworkIdle",
    status: "partial",
    notes: "Uses Crater runtime network-idle helpers.",
  },
  {
    owner: "page",
    api: "waitForTimeout",
    status: "supported",
    notes: "Resolves after the requested host-side timeout.",
  },
  {
    owner: "page",
    api: "waitForNavigation",
    status: "partial",
    notes: "Resolves on subscribed BiDi load/domContentLoaded events.",
  },
  {
    owner: "page",
    api: "setViewport",
    status: "crater-extension",
    notes: "Crater BiDi extension for layout/VRT control.",
  },
  {
    owner: "page",
    api: "captureScreenshot",
    status: "crater-extension",
    notes: "Crater BiDi screenshot data helper.",
  },
  {
    owner: "page",
    api: "screenshot",
    status: "partial",
    notes: "Playwright-style alias for Crater screenshot capture.",
  },
  {
    owner: "page",
    api: "capturePaintData",
    status: "crater-extension",
    notes: "Crater BiDi RGBA paint capture helper.",
  },
  {
    owner: "page",
    api: "capturePaintTree",
    status: "crater-extension",
    notes: "Crater BiDi paint tree capture helper.",
  },
  {
    owner: "page",
    api: "getComputedStyles",
    status: "crater-extension",
    notes: "Crater computed style inspection helper.",
  },
  {
    owner: "page",
    api: "getComputedStylesBySharedId",
    status: "crater-extension",
    notes: "Crater computed style inspection helper.",
  },
  {
    owner: "page",
    api: "getAllComputedStyles",
    status: "crater-extension",
    notes: "Crater computed style inspection helper.",
  },
  {
    owner: "page",
    api: "getComputedStylesForElement",
    status: "crater-extension",
    notes: "Crater computed style inspection helper.",
  },
  {
    owner: "page",
    api: "getCssRuleUsage",
    status: "crater-extension",
    notes: "Crater CSS rule usage inspection helper.",
  },
  {
    owner: "page",
    api: "getCssRuleUsageDetails",
    status: "crater-extension",
    notes: "Crater CSS rule usage inspection helper.",
  },
  {
    owner: "locator",
    api: "locator",
    status: "partial",
    notes: "Chains a child locator under the first matching parent.",
  },
  {
    owner: "locator",
    api: "filter",
    status: "partial",
    notes: "Supports hasText/hasNotText filters with Playwright-style whitespace normalization.",
  },
  {
    owner: "locator",
    api: "getByText",
    status: "partial",
    notes: "Child text locator.",
  },
  {
    owner: "locator",
    api: "getByRole",
    status: "partial",
    notes: "Child role locator with the same partial role/name support as page.getByRole.",
  },
  {
    owner: "locator",
    api: "first",
    status: "supported",
    notes: "Selects the first match.",
  },
  {
    owner: "locator",
    api: "last",
    status: "supported",
    notes: "Selects the last match.",
  },
  {
    owner: "locator",
    api: "nth",
    status: "supported",
    notes: "Selects a zero-based match.",
  },
  {
    owner: "locator",
    api: "click",
    status: "supported",
    notes: "Calls element.click() in the Crater runtime.",
  },
  {
    owner: "locator",
    api: "hover",
    status: "partial",
    notes: "Dispatches pointerenter/mouseover events in the Crater runtime.",
  },
  {
    owner: "locator",
    api: "focus",
    status: "partial",
    notes: "Focuses the element when available and dispatches focus/focusin events.",
  },
  {
    owner: "locator",
    api: "fill",
    status: "supported",
    notes: "Sets value and dispatches input/change events.",
  },
  {
    owner: "locator",
    api: "clear",
    status: "supported",
    notes: "Clears value and dispatches input/change events.",
  },
  {
    owner: "locator",
    api: "type",
    status: "partial",
    notes: "Appends text and dispatches input events; full keyboard semantics are not implemented.",
  },
  {
    owner: "locator",
    api: "press",
    status: "partial",
    notes: "Dispatches keydown/keyup and applies simple text input edits.",
  },
  {
    owner: "locator",
    api: "dispatchEvent",
    status: "partial",
    notes: "Dispatches Event or CustomEvent with serializable init data.",
  },
  {
    owner: "locator",
    api: "check",
    status: "supported",
    notes: "Sets checkbox/radio checked state and dispatches input/change events.",
  },
  {
    owner: "locator",
    api: "uncheck",
    status: "supported",
    notes: "Clears checkbox checked state and dispatches input/change events.",
  },
  {
    owner: "locator",
    api: "selectOption",
    status: "partial",
    notes: "Selects a single option by value and dispatches input/change events.",
  },
  {
    owner: "locator",
    api: "evaluate",
    status: "partial",
    notes: "Evaluates a serializable function against the first matching element, with optional JSON-serializable arg support.",
  },
  {
    owner: "locator",
    api: "evaluateAll",
    status: "partial",
    notes: "Evaluates a serializable function against all matching elements, with optional JSON-serializable arg support.",
  },
  {
    owner: "locator",
    api: "allTextContents",
    status: "supported",
    notes: "Returns textContent for all matching elements.",
  },
  {
    owner: "locator",
    api: "allInnerTexts",
    status: "partial",
    notes: "Returns innerText when available, falling back to textContent.",
  },
  {
    owner: "locator",
    api: "textContent",
    status: "supported",
    notes: "Returns element textContent.",
  },
  {
    owner: "locator",
    api: "innerHTML",
    status: "supported",
    notes: "Returns element innerHTML.",
  },
  {
    owner: "locator",
    api: "inputValue",
    status: "supported",
    notes: "Returns element value.",
  },
  {
    owner: "locator",
    api: "isVisible",
    status: "partial",
    notes: "Checks hidden/display/visibility.",
  },
  {
    owner: "locator",
    api: "isHidden",
    status: "partial",
    notes: "Inverse of Crater isVisible().",
  },
  {
    owner: "locator",
    api: "isChecked",
    status: "supported",
    notes: "Returns checked state.",
  },
  {
    owner: "locator",
    api: "isDisabled",
    status: "partial",
    notes: "Checks disabled property or attribute.",
  },
  {
    owner: "locator",
    api: "isEnabled",
    status: "partial",
    notes: "Inverse of Crater isDisabled().",
  },
  {
    owner: "locator",
    api: "isEditable",
    status: "partial",
    notes: "Checks simple input/textarea/contenteditable editability.",
  },
  {
    owner: "locator",
    api: "getAttribute",
    status: "supported",
    notes: "Returns element getAttribute.",
  },
  {
    owner: "locator",
    api: "waitFor",
    status: "supported",
    notes: "Polls until a matching element exists.",
  },
  {
    owner: "locator",
    api: "count",
    status: "supported",
    notes: "Returns match count.",
  },
] as const satisfies readonly CraterPlaywrightApiEntry[];

export function craterPlaywrightApisFor(owner: CraterPlaywrightApiOwner) {
  return CRATER_PLAYWRIGHT_API_SUPPORT.filter((entry) => entry.owner === owner);
}
