/**
 * CDP WebSocket Server
 *
 * WebSocket server for Chrome DevTools Protocol.
 * Connects puppeteer-core to the MoonBit CDP implementation.
 *
 * Usage:
 *   npx tsx tools/cdp-server.ts [port]
 *
 * Default port: 9222
 */

import { WebSocketServer, WebSocket } from 'ws';
import { createServer, IncomingMessage, ServerResponse } from 'http';

// Import the MoonBit CDP module
// @ts-ignore - generated by moon build
import * as cdp from '../target/js/release/build/src/cdp_js/cdp_js.js';

const PORT = parseInt(process.argv[2] || '9222', 10);

// Track active connections
const connections = new Set<WebSocket>();

// HTTP server for /json endpoints (required by puppeteer)
const httpServer = createServer((req: IncomingMessage, res: ServerResponse) => {
  const url = req.url || '/';
  console.log(`HTTP ${req.method} ${url}`);

  res.setHeader('Content-Type', 'application/json');

  if (url === '/json/version') {
    res.end(JSON.stringify({
      Browser: 'Crater/1.0',
      'Protocol-Version': '1.3',
      'User-Agent': 'Crater',
      'V8-Version': '0.0.0',
      'WebKit-Version': '0.0.0',
      webSocketDebuggerUrl: `ws://localhost:${PORT}/devtools/browser`,
    }));
    return;
  }

  if (url === '/json' || url === '/json/list') {
    res.end(JSON.stringify([{
      description: '',
      devtoolsFrontendUrl: '',
      id: 'page-1',
      title: 'Crater Page',
      type: 'page',
      url: 'about:blank',
      webSocketDebuggerUrl: `ws://localhost:${PORT}/devtools/page/page-1`,
    }]));
    return;
  }

  if (url === '/json/new') {
    res.end(JSON.stringify({
      description: '',
      devtoolsFrontendUrl: '',
      id: 'page-1',
      title: 'Crater Page',
      type: 'page',
      url: 'about:blank',
      webSocketDebuggerUrl: `ws://localhost:${PORT}/devtools/page/page-1`,
    }));
    return;
  }

  res.statusCode = 404;
  res.end(JSON.stringify({ error: 'Not found' }));
});

// WebSocket server
const wss = new WebSocketServer({ server: httpServer });

wss.on('connection', (ws: WebSocket, req: IncomingMessage) => {
  console.log(`WebSocket connection: ${req.url}`);
  connections.add(ws);

  // Reset protocol state for new connection
  cdp.resetCdpProtocol();

  ws.on('message', (data: Buffer) => {
    const message = data.toString();
    console.log(`<- ${message.substring(0, 200)}${message.length > 200 ? '...' : ''}`);

    try {
      // Process message through MoonBit CDP
      const response = cdp.processCdpMessage(message);
      console.log(`-> ${response.substring(0, 200)}${response.length > 200 ? '...' : ''}`);
      ws.send(response);

      // Send any pending messages (events)
      let pending = cdp.hasPendingCdpMessages();
      while (pending > 0) {
        const pendingMsg = cdp.getNextCdpMessage();
        if (pendingMsg) {
          console.log(`-> [event] ${pendingMsg.substring(0, 200)}${pendingMsg.length > 200 ? '...' : ''}`);
          ws.send(pendingMsg);
        }
        pending = cdp.hasPendingCdpMessages();
      }
    } catch (err) {
      console.error('Error processing message:', err);
      const errorResponse = JSON.stringify({
        error: { code: -32603, message: String(err) }
      });
      ws.send(errorResponse);
    }
  });

  ws.on('close', () => {
    console.log('WebSocket closed');
    connections.delete(ws);
  });

  ws.on('error', (err) => {
    console.error('WebSocket error:', err);
  });
});

httpServer.listen(PORT, () => {
  console.log(`Crater CDP server listening on port ${PORT}`);
  console.log(`WebSocket: ws://localhost:${PORT}/devtools/browser`);
  console.log(`HTTP API: http://localhost:${PORT}/json/version`);
  console.log(`\nConnect with puppeteer-core:`);
  console.log(`  const browser = await puppeteer.connect({`);
  console.log(`    browserWSEndpoint: 'ws://localhost:${PORT}/devtools/browser'`);
  console.log(`  });`);
});
